### ISSUE TITLE
MacOS backend

### ISSUE THREAD

**Issue by SamoZ256** [Immanuel-C/IWindow#6]
This library seems really nice, but it lacks MacOS backend. I would be willing to work on it, maybe under some experimental branch.

**Comment by Immanuel-C** [comment]
Sure @SamoZ256, I currently don't have a Mac and I wanted to do this. I haven't been really active on this project but I want to add some more features and a MacOS backend would be amazing.

**Comment by SamoZ256** [comment]
So I've started working on it, but there's a problem (mainly from the design point of view). All the callbacks and events need to be processed in separate objective-c classes, and those classes do not have access to the private members of IWindow::Window (for example m_running). How should I handle this? Create public setters?

**Comment by SamoZ256** [comment]
I have managed to create a rough implementation. The TestWindow test compiles and runs fine, but it's most likely missing a lot of functionality. Should I open a pull request?

**Comment by Immanuel-C** [comment]
@SamoZ256 Making public setters will be fine. Also is Objective C necessary?

**Comment by Immanuel-C** [comment]
Also I will make a new experimental branch for the macOS code until it is stable and has all the features the win32 version does. please push your changes to it.

**Comment by SamoZ256** [comment]
> @SamoZ256 Making public setters will be fine. Also is Objective C necessary?
> 
> 
> 
> 

Unfortunately yes. Cocoa is an Objective-c framework
